name: Build ChineseSubFinder DockerImage-Beta

on:
  push:
    tags:
      - v*.*-Beta*
      - v*.*-DockerBeta*
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 获取 tag 版本
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push
      - name: Build dockerfile
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/chinesesubfinder:${{ steps.set-version.outputs.version }}
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          secrets: |
            "BASEKEY=${{ secrets.BASEKEY }}"
            "AESKEY16=${{ secrets.AESKEY16 }}"
            "AESIV16=${{ secrets.AESIV16 }}"
