name: goreleaser-ChineseSubFinder

on:
  push:
    tags:
      - v*.*-Beta*
      - v*.*-ExeBeta*
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup npm
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: frontend install depandence
        run: npm ci
        working-directory: frontend

      - name: frontend build
        run: npm run build
        working-directory: frontend

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser-ChineseSubFinder.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          BASEKEY: ${{ secrets.BASEKEY }}
          AESKEY16: ${{ secrets.AESKEY16 }}
          AESIV16: ${{ secrets.AESIV16 }}
